### ISSUE TITLE
?asset broken

### ISSUE THREAD

**Issue by Thundermaker300** [Thundermaker300/Roblox-Wikia-Bot#11]
oh no

**Comment by MikhailMCraft** [comment]
yes this helps us solve the bug

**Comment by Thundermaker300** [comment]
4 days in and I've spent approximately 0 minutes looking into this

**Comment by Michael105YT** [comment]
great

**Comment by Thundermaker300** [comment]
Isn't it exciting

**Comment by userterminal** [comment]
Issue Revive

**Comment by Thundermaker300** [comment]
Spent like 3 minutes looking at this then got distracted
